#!/bin/bash
# -*- mode: shell-script; coding: utf-8-emacs-unix; sh-basic-offset: 8; indent-tabs-mode: t -*-

workdir="$(readlink -f $(dirname $0))"
. $workdir/core.sh || exit 1

if [[ -z $1 ]]; then
	die "You shouldn't run this."
fi

source="$1"
if [[ ! -z $2 ]]; then
	target="$initramfs_root/bin/$(basename $2)"
else
	target="$initramfs_root/bin/$(basename $source)"
fi

addbin() {
	einfo "Adding $source..."
	if ! ldd $source >> /dev/null; then
		$sudo cp -p $source $target # static link file
	else
		$sudo cp -p $source $target # dynamic link file, copy dynamic library
		dynamic_libs=$(ldd $source | \
			awk '{if (NF==4) print $3; if (NF==2) print $1}')
		for lib in $dynamic_libs; do
			libdir=$(dirname "${initramfs_root}${lib}")
			[ -d $libdir ] || mkdir -p $libdir
			[ -e "${initramfs_root}/${lib}" ] || (
				einfo "Adding dynamic library: $lib"
				if [ -h $lib ]; then
					cp -p $(readlink -f $lib) $libdir
					ln -s $(readlink $lib) ${libdir}/$(basename $lib)
				else
					cp -p $lib $libdir
				fi
			)
			set +x
		done
	fi
}

if [[ -f $source ]]; then
	if [[ -f $target ]] && [[ $(md5sum $source | cut -d " " -f 1) != $(md5sum $target | cut -d " " -f 1) ]]; then ewarn "Looks like we have old copy of '$source'. Upgrading..." && addbin; fi
	if [[ ! -f $target ]]; then addbin; fi
else 
	ewarn "Missing binary: $source, skipping."
fi
